// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5IuxclQEMdXg57sv6RHah65R3g2TXIvs',
    appId: '1:968194436942:web:5806e60b3dd24bbd6fb81f',
    messagingSenderId: '968194436942',
    projectId: 'zooplehackathon',
    authDomain: 'zooplehackathon.firebaseapp.com',
    storageBucket: 'zooplehackathon.firebasestorage.app',
    measurementId: 'G-PJTEG6V797',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnWcSHCr6O9-yRaeJPAMnPz7jt6vS0hQ4',
    appId: '1:968194436942:android:f7a18ca73d69d55f6fb81f',
    messagingSenderId: '968194436942',
    projectId: 'zooplehackathon',
    storageBucket: 'zooplehackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdw8T-r0bBa4jTLJUzDkxE1u-T2XDVHgA',
    appId: '1:968194436942:ios:a8c53f7a003e02346fb81f',
    messagingSenderId: '968194436942',
    projectId: 'zooplehackathon',
    storageBucket: 'zooplehackathon.firebasestorage.app',
    iosBundleId: 'com.example.zh2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdw8T-r0bBa4jTLJUzDkxE1u-T2XDVHgA',
    appId: '1:968194436942:ios:a8c53f7a003e02346fb81f',
    messagingSenderId: '968194436942',
    projectId: 'zooplehackathon',
    storageBucket: 'zooplehackathon.firebasestorage.app',
    iosBundleId: 'com.example.zh2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5IuxclQEMdXg57sv6RHah65R3g2TXIvs',
    appId: '1:968194436942:web:fa721cd78beccab76fb81f',
    messagingSenderId: '968194436942',
    projectId: 'zooplehackathon',
    authDomain: 'zooplehackathon.firebaseapp.com',
    storageBucket: 'zooplehackathon.firebasestorage.app',
    measurementId: 'G-XFQ87YTR99',
  );
}
